server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_NAME:myappdb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
